// <auto-generated />
using JaMoveo.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaMoveo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250706120943_DropTodoItemsTable")]
    partial class DropTodoItemsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");
#pragma warning restore 612, 618
        }
    }
}
